### ISSUE TITLE
在不同品牌手机上的适配问题

### ISSUE THREAD

**Issue by lmykjj** [yinote/android#107]
要适应于不同的手机，例如字体的大小，icon的大小

**Comment by lmykjj** [comment]
![20141110_143352](https://cloud.githubusercontent.com/assets/8372948/4972198/c02fb38e-68a7-11e4-884c-50b94b6c0c72.jpg)

**Comment by lmykjj** [comment]
大屏手机的内容字体依旧很大

**Comment by luhui2014** [comment]
基本改完。1.6.0版本有些字体较大，1.7.0版本已修正。
