### ISSUE TITLE
输入表情时，标题中显示乱码

### ISSUE THREAD

**Issue by lmykjj** [yinote/android#108]
在笔记内容中显示的是乱码，而在标题中显示正常。

**Comment by lmykjj** [comment]
![20141110_133128](https://cloud.githubusercontent.com/assets/8372948/4972700/fbc3f70e-68af-11e4-95e5-2049b3dcb45f.jpg)
![20141110_133118](https://cloud.githubusercontent.com/assets/8372948/4972701/fbca1878-68af-11e4-9833-0f0e1c1151b8.jpg)

**Comment by luhui2014** [comment]
仿照有道的解决方案，当解析表情出现乱码时，用空代替。
