### ISSUE TITLE
未登录状态下，新建笔记界面顶部没有显示笔记本名称（偶发性）

### ISSUE THREAD

**Issue by lmykjj** [yinote/android#109]
新建笔记界面的顶部应该会有笔记所属的笔记本名称

**Comment by lmykjj** [comment]
![20141110_143352](https://cloud.githubusercontent.com/assets/8372948/4972237/54ec1508-68a8-11e4-9308-4cf3e55e3c6c.jpg)

**Comment by luhui2014** [comment]
以解决
