### ISSUE TITLE
待办事项中，能够添加空的待办事项

### ISSUE THREAD

**Issue by lmykjj** [yinote/android#110]
1、先新建一个待办事项，设置一个标签和时间提醒，然后删除输入的待办事项内容，再保存，应该是显示内容不能为空，可是却依旧可以新建。
2、内容写完，用户想再次编辑时，应该是点击编辑界面任意一个地方输入法都会弹出，可是现在必须是光标在文字中才会跳出来

**Comment by lmykjj** [comment]
![1](https://cloud.githubusercontent.com/assets/8372948/4972367/5d1d8e3a-68aa-11e4-84ac-ec2ddd0a9123.png)

**Comment by luhui2014** [comment]
以解决

**Comment by viczhao** [comment]
新建待办；选择标签（假设红），不输入标题，点空白；再新建待办，输入标题，不选择标签，点空白生成待办，会有标签红。
