### ISSUE TITLE
网络不稳定时的提示优化

### ISSUE THREAD

**Issue by yb7** [yinote/android#88]
涉及笔记列表，笔记内容，评论等加载

参考“网易新闻”
1. 点击屏幕，重新加载
2. 下方闪出“网络不给力”，两秒后黑框自动消失。

![screenshot_2014-04-25-16-05-26](https://cloud.githubusercontent.com/assets/678122/2800247/997229b8-cc6f-11e3-9e7d-03665c6d4076.png)

**Comment by long33boy** [comment]
已提交，提交日志写错了
